services:
  fitnessportaldb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  fitnessportalapi:
    image: ${DOCKER_REGISTRY-}fitnessportalapi
    build:
      context: .
      dockerfile: FitnessPortalAPI/Dockerfile

  fitnessportalclient:
    image: ${DOCKER_REGISTRY-}fitnessportalclient
    build:
      context: ../FitnessPortalFRONTEND
      dockerfile: /Dockerfile
    depends_on:
      - fitnessportalapi
    ports:
      - "5173:5173"

