name: API CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'

      - name: Restore API dependencies
        run: dotnet restore ./FitnessPortalBACKEND/FitnessPortalAPI/FitnessPortalAPI.csproj

      - name: Build API
        run: dotnet build --configuration Release --no-restore ./FitnessPortalBACKEND/FitnessPortalAPI/FitnessPortalAPI.csproj

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'

      - name: Restore test project dependencies
        run: dotnet restore ./FitnessPortalBACKEND/FitnessPortalAPI.Tests/FitnessPortalAPI.Tests.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore ./FitnessPortalBACKEND/FitnessPortalAPI.Tests/FitnessPortalAPI.Tests.csproj

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal ./FitnessPortalBACKEND/FitnessPortalAPI.Tests/FitnessPortalAPI.Tests.csproj